### PR TITLE
fix_382

### LINKED ISSUE #382: getQuote.yahoo 401 error
EDIT by @joshuaulrich:

## Read me first!

1. If you came here to report the same issue, please upvote this issue report instead of adding a comment to the thread. That helps keep the comments clean and informative. I may delete comments that are equivalent to "I'm having the same problem", "the patch worked for me", "the patch didn't work", or comments about not being able to install development versions that address this issue.

1. If you tried one of the potential solutions and it didn't work, please provide the exact version of the code you're using and the error you received. Saying, "it didn't work" isn't enough information to be helpful.

## What's the problem?
It looks like Yahoo started using cookies for the quote portion of the v7 API. We had been using cookies for historical prices with the v7 API, until we switched to the v8 API for historical prices in the last release.

Using the v7 API with cookies for quotes seems to work for most people who aren't subject to GDPR restrictions. The v7 patch for `getQuote()` doesn't work for those who are affected by GDPR because they have to accept GDPR before they can use the v7 API, but that's not easy to implement in `getQuote()`.

## Where can I get a patched version?

1. As of 2023-05-05, PR #382 seems to work for most people. Run the R code below to get the patch. Make sure the installed package version matches.

    ```r
    remotes::install_github("ethanbsmith/quantmod@382_add_session_getQuote")
    packageVersion("quantmod")  # should be '0.4.22.1'
    ```

## Are there other work-arounds?

1. @scheb found that using version "v6" works, and @gjmulder [provided a patch](https://github.com/joshuaulrich/quantmod/issues/382#issuecomment-1537828884) for quantmod, if you're comfortable updating and installing from source.

1. @theinvestmentbox suggested using `yfinance::get_price()`. You can install it via `remotes::install_github("ljupch0/yfinance")`.

/EDIT

----

`getQuote` started intermittently returning a 401 error on 2023-04-18.

```r
> getQuote("SPY;IBM", src = "yahoo")
## Error in open.connection(con, "rb") : HTTP error 401.
```

The direct URL (https://query1.finance.yahoo.com/v7/finance/quote?symbols=SPY,TSLA) gives the full error as a JSON response.

```json
{
    "finance": {
        "result": null,
        "error": {
            "code": "Unauthorized",
            "description": "Invalid Crumb"
        }
    }
}
```

### Session Info

```r
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C
[5] LC_TIME=English_United States.utf8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] kableExtra_1.3.4   rio_0.5.29         rvest_1.0.3        xml2_1.3.3
 [5] Rcpp_1.0.10        matrixStats_0.63.0 data.table_1.14.8  doFuture_1.0.0
 [9] future_1.32.0      doParallel_1.0.17  iterators_1.0.14   foreach_1.5.2
[13] quantmod_0.4.22    TTR_0.24.3.1       xts_0.13.0         zoo_1.8-11
```

### PR DESCRIPTION
**Pull request by ethanbsmith**
adds a lightweight session for use on yahoo quote requests
session is needed for both the cookies and the "crumb" field
the handle from the session must also be used for subsequent requests
fixes #382

### CODE REVIEW

**Comment by pstadler** [comment]
I thought I'd be a nice neighbor and let you know that certain regions (probably EU) seem to get redirected to a consent page during the initial call failing to obtain a session. We're currently investigating possible solutions:
https://github.com/pstadler/ticker.sh/issues/33#issuecomment-1517340591

**Comment by ethanbsmith** [comment]
thx @pstadler. it looks like the cookies and crumbs are no longer needed again for v7 (at least for now). r u seeing the redirects on calls to the v7 api w/out simulating a session?

**Comment by pstadler** [comment]
it‘s happening over at my project using something very similar to your fix. Going to remove it again if it‘s working again without crumb. Wondering for how long though, it‘s been flaky for a while.

**Comment by pstadler** [comment]
I gladly reverted the change on my end. Fingers crossed that it won't happen again.

**Comment by ethanbsmith** [comment]
im currently testing an update that caches the yahoo handle. i dont know what the error will ben when the handle becomes invalid, as this is probably driven by a timeout on the yahoo server side, so i cant force the error condition. will push once i have that part worked out

**Comment by pstadler** [comment]
my assumption is that’s you‘ll get a 401 Unauthorized if the session expires (if this is what you’re referring to). In this case I‘d simply try to obtain a new session and fetch the quotes again. See https://github.com/pstadler/ticker.sh/blob/54b73a3f57432b5efd102754c48f20ed246f8ed2/ticker.sh#L53

**Comment by ethanbsmith** [comment]
josh, with the handle caching, performance is now pretty much on par w/ the prior version. also, when yahoo removed this check last week, passing in the crumb still worked fine. so, i dont think there is any downside to having this code in production as it should work either way.

File: R/getQuote.R [hunk 1]
```diff
@@ -24,11 +24,46 @@ function(Symbols,src='yahoo',what, ...) {
...
+  if (ses$can.crumb) {
+    #get a crumb so that downstream callers dont have to handle invalid sessions.
+    #this is a network hop, but very lightweight payload
+    n <- if (unclass(Sys.time()) %% 1L >= 0.5) 1L else 2L
+    query.srv <- paste0("https://query", n, ".finance.yahoo.com/v1/test/getcrumb")
+    r <- curl::curl_fetch_memory(query.srv, handle = ses$h)
+    if ((r$status_code == 200) && (length(r$content) > 0)) {
+      ses$crumb = rawToChar(r$content)
+    } else {
+      if (!force.new) ses <- .yahooSession(TRUE) else stop("Unable to get yahoo crumb")
```
Comment (joshuaulrich) [inline R/getQuote.R:54]: This seems backward. I expect to call `.yahooSession(TRUE)` when `force.new` is `TRUE`, else throw an error because we can't get a crumb.

Comment (ethanbsmith) [reply R/getQuote.R:54]: its really a state machine. the `force.new` is never intended to be used directly, only in the recursive call. i can rewrite it as a loop to clean up the signature

Comment (joshuaulrich) [reply R/getQuote.R:54]: Calling the function recursively is fine. The logic on this line (51) confused me, but seems correct once I walk through it.

Assume `force.new` is `FALSE`. Line 45 checks that we have an active session. Line 51 checks if we're able to get a crumb. If we can't get a crumb, then `!force.new` is `TRUE` and we call `.yahooSession(TRUE)`. So that seems like it does what it should.

I think some comments would help me remember what this is doing.

```r
# we were unable to get a crumb
if (force.new) {
    # we couldn't get a crumb with a new session
    stop("unable to get yahoo crumb")
} else {
    # we tried to re-use a session but couldn't get a crumb
    # try to get a crumb using a new session
    ses <- .yahooSession(TRUE)
}
    
```

**Comment by rdheller** [comment]
Same problem - "could not find function "getQuote".  Used it two days ago, but can't use it today.  2/17/2025.  I'm looking for anyone who can help!
